.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_spec.md, .github/pull_request_template.md
Adding github templates for the following:
- Bug report issues
- Feature specification issues
- Pull requests
=> Adding issue and pull request templates

go.mod, go.sum, vms/evm/contract_message_test.go
Bumps subnet-evm to v0.5.4 and avalanchego to v1.10.9
CI
=> subnet-evm v0.5.4

.github/dependabot.yml
We want to depend on geth implicitly via subnet-evm and avalanchego. We still use geth libraries, but we should only update them in tandem with subnet-evm and avalanchego.
Adds `go-ethereum` to dependabot ignore
=> Ignore geth updates in Dependabot

.github/workflows/linter.yml, .golangci.yml, config/config_test.go, main/main.go, peers/external_handler.go, relayer/message_relayer.go, relayer/relayer.go, scripts/lint.sh, vms/evm/contract_message_test.go
- Add a linter for go files with set lint rules and a github workflow.
- Use Github Action for running [golangci-lint](https://github.com/golangci/golangci-lint) 
- CI
=> Add a Go linter to CI

config/config.go, config/config_test.go, config/keys.go, database/database.go, database/json_file_storage.go, database/json_file_storage_test.go, main/main.go, peers/external_handler.go, relayer/message_relayer.go, relayer/relayer.go, vms/evm/contract_message.go, vms/evm/subscriber.go, vms/subscriber.go, vms/vmtypes/message_info.go
Enables the relayer to process warp messages sent while the relayer was offline. Fixes https://github.com/ava-labs/awm-relayer/issues/14
Adds a `ProcessFromHeight` method to `Subscriber`. The EVM implementation calls `eth_getLogs` to retrieve Warp logs since the last processed block. Adds JSON storage to persist the last processed block.
CI, Teleporter integration tests, added unit tests for JSON storage, manual testing. Will circle back and add end-to-end tests once https://github.com/ava-labs/awm-relayer/issues/15 is complete.
=> Process missed blocks on startup

.github/workflows/release.yaml
Release action for publish docker image is failing, this hopes to address and fix.
for `build-push-action` [docs](https://github.com/docker/build-push-action/tree/v5/#git-context), specifies we use git context without the `checkout` action, or if we use `checkout` action we should pass in path `context`. So this PR is adding the path context since we do use `checkout` action.
n/a
n/a
=> use docker build path context

peers/app_request_network.go
Currently the P-Chain API URL passed in the config is used for two purposes:
- To get the canonical validator set for a subnet
- To establish peers in the app request network via the info API
The latter case requires that the info API expose the `GetNodeIP` method on the node. For the public RPC (api.avax.network), this method is disabled.
Removes the calls to the methods `GetNodeIP` and `GetNodeID` on the configured P-Chain API node. Instead, we get the list of peer IPs and IDs from `GetPeers`, which is enabled on the public RPC server. 
Also fixes an edge case in which it's possible to connect to fewer than the intended number of peers on startup.
CI
N/A
=> Simplify info client usage

.github/workflows/e2e.yml, .github/workflows/linter.yml, .github/workflows/test.yml, Dockerfile, scripts/build.sh, scripts/build_local_image.sh, scripts/versions.sh
Creates a single source of truth for pulling the golang version, as well as deps like ginkgo and subnet-evm.
=> Single source of truth for go version

.github/dependabot.yml
The current dependabot ignore config is not correctly ignoring for `go-ethereum`, and we also want to ignore for avalanchego, since that version needs to be compatible with `subnet-evm` version
=> Update dependabot ignore

scripts/versions.sh
Addresses [CVE-2023-39326](https://www.cve.org/CVERecord?id=CVE-2023-39326).
Updates the minimum golang version to include https://github.com/golang/go/issues/64434.
CI
N/A
=> Golang 1.20.12

Dockerfile, scripts/build_local_image.sh
Docker Compose files will pick up exported env vars, but plain dockerfiles won't, so we have to specify it to pass it in.
Also an `ARG` in a dockerfile's scope only lasts until the next `FROM` directive.
=> Pass in GO_VERSION explicitly to dockerfile

.github/workflows/release.yaml
The release workflow needs the golang version to be set so it can grab the right docker images to build with.
=> Set go version for dockerfile release

.github/workflows/e2e.yml, .github/workflows/linter.yml, .github/workflows/release.yaml, .github/workflows/test.yml, CONTRIBUTING.md, go.mod, scripts/build.sh
`GO_VERSION=$GO_VERSION >> $GITHUB_ENV` is not a proper bash command, so was failing, but silently for some reason. This was causing the env var not to be set, so the `go-version` in `actions/setup-go@v5` was defaulting to `1.20.11`
=> Set go version properly in workflows

.github/workflows/e2e.yml
Keeps the e2e tests up-to-date with the version of `subnet-evm` in the `go.mod` file.
We use `versions.sh` to get the proper version from `go.mod`.
E2E tests in CI
N/A
=> Sync subnet-evm versions in e2e tests

config/config.go, config/config_test.go
We reimplemented populating the private key struct before we knew that the crypto library would do it for us.
Uses crypto library to create a private key from a hex string.
existing tests
=> Use crypto library for private keys

messages/message_manager.go, messages/teleporter/message_manager.go, messages/teleporter/message_manager_test.go, relayer/relayer.go, vms/evm/subscriber.go, vms/vmtypes/message_info.go
Closes https://github.com/ava-labs/awm-relayer/issues/131
The only place that gives back a `common.Hash` is the warp logs. We convert this into a `common.Address` instead of the other way around.
Existing tests
=> Use common.Address instead of common.Hash

messages/teleporter/message_manager.go, messages/teleporter/message_manager_test.go
Closes https://github.com/ava-labs/awm-relayer/issues/136, supersedes https://github.com/ava-labs/awm-relayer/pull/160
Uses a utility in the Teleporter repo to calculated the Teleporter Message ID without having to make an API call to a node.
Tested in the Teleporter repo.
=> Use teleporter message ID utility

go.mod, messages/teleporter/message_manager_test.go, vms/evm/destination_client_test.go, vms/evm/subscriber_test.go
The error printed would indicate the wrong test case failing. We want to log the actual test case that fails.
Also add additional check and test case for `ProcessFromHeight`
We need to create the go mock controllers with `gomock.NewController(t)` while we iterate through the test cases to get the correct test case that fails printed in error.
If you make one of `TestShouldSendMessage` or `TestSendTx` fail on `main` it will print the error indicating the wrong test case failing. Compared to this branch, it'll indicate the correct test case.
For example, I had `TestShouldSendMessage/not_allowed` fail on `main`, but the error prints 
```
--- FAIL: TestShouldSendMessage/message_already_delivered (0.00s)
testing.go:1490: test executed panic(nil) or runtime.Goexit: subtest may have called …
```
=> Improve tests error handling

.github/workflows/release.yml, .goreleaser.yml, Dockerfile, Dockerfile.release
Changes the base image layer of the Dockerfile from `debian:11-slim` to `golang:v1.21.7`. The golang layer contains a wider set of pre-installed binaries necessary for the relayer to work in a cloud environment. For example, `debian:11-slim` does not contain TLS certs, while to golang layer does.
- Replaces `debian:11-slim` with `golang:v1.21.7`
- Removes the unused Dockerfile
Tested by creating release [v0.0.1](https://github.com/ava-labs/awm-relayer/releases/tag/v0.0.1), and testing the published image on darwin/arm64 and linux/amd64 systems.
- This release will be removed after this PR is merged.
N/A
=> Update release Dockerfile

README.md
The description of the `supported-destinations` configuration option is wrong. See how the option is used:
https://github.com/ava-labs/awm-relayer/blob/9eb28ffcfac2bf690bb74be50463d93c0380c6ac/config/config.go#L447-L458
Fixes the description
NA
NA
=> fix: correct supported-destinations option description

README.md, config/config.go, config/config_test.go, config/keys.go, main/main.go, relayer/relayer.go, tests/basic_relay.go, tests/utils/utils.go, vms/contract_message.go, vms/destination_client.go, vms/evm/contract_message.go, vms/evm/contract_message_test.go, vms/evm/destination_client.go, vms/evm/destination_client_test.go, vms/evm/subscriber.go, vms/evm/subscriber_test.go, vms/subscriber.go
Fixes #170 
The application requires unique Blockchain IDs in the configuration, but the naming suggests that Subnets also need to be unique. Subnets can contain multiple blockchains, in which case there would need to be multiple entries in `SourceSubnets` and `DestinationSubnets` with the same subnet ID.
Renames `SourceSubnet` to `SourceBlockchain` and `DestinationSubnet` to `DestinationBlockchain` in the configuration.
CI
Updated README
=> Rename subnet -> blockchain in Config

README.md, peers/app_request_network.go
When the so called API node is inside the validator set for the source blockchain, it is not added itself as it is not a peer of himself (only peers to API node are added). In situations were that validator is needed to fully sign a msg, teleporter can't proceed beyond relayer step. 
The API node adds himself is belonging to the validators set
It was tested on teleporter deploys on fuji for subnets of only one validator.
=> add api node to network if it is a validator

README.md
Adds a oneliner summary to the top-level README. The high-level explanation is useful to have in the repo, as well as in places where the README will be embedded, such as avalanche-docs.
=> Add readme one-liner

README.md, config/config.go, config/keys.go, relayer/relayer.go, relayer/relayer_test.go, tests/basic_relay.go, tests/utils/utils.go
Previously, we were using `process-missed-blocks` to determine whether to process historical AND missed blocks. This PR splits those out into two different config options.
`process-historical-blocks` defaults to `false` will only work if `start-block-height` is set, and will start processing blocks from the greater of `start-block-height` and the last processed block height (if it exists in the db).
`process-missed-blocks` defaults to `true`, and will start processing blocks from the last processed block height (if it exists in the db). If there is no latest block in the db, or `process-missed-blocks` is `false`, we will start processing from the chain head.
README
=> Simplify options for process-historical-blocks

.devcontainer/devcontainer.json, .gitignore, README.md, config/config.go, sample-relayer-config.json
Make the awm-relayer easily accessible to a wider range of developers independent of their operating system and system setup. 
By leveraging [devcontainers](https://code.visualstudio.com/docs/devcontainers/containers) the developers can open the repository either in a [Codespace](https://github.com/features/codespaces) or locally in a docker container.
Manually
Added a note to the readme
=> Add devcontainer config and sample relayer config

go.mod, go.sum, sample-relayer-config.json, scripts/versions.sh
=> Integrate Teleporter v1.0.0

README.md
We are importing the awm-relayer readme in the documentation at docs.avax.network. For these docs we have a linter running to ensure consistent wording and spelling accross all docs pages
- Capitalize "Subnet"
- e.g. => for example
- fix types
- header casing
n/a
n/a
=> Fix docs lint errors

README.md
=> formating readme for docs

README.md
Documents some common pitfalls that may cause P2P connections to fail, especially on new test subnets consisting of a single node.
=> Add p2p requirements

config/config.go
Until ```subnet-evm``` fixes this issue in the next release, this workaround will fix https://github.com/ava-labs/awm-relayer/issues/226
=> Workaround: Ensure all preocompile modules are registered

README.md, config/config.go, config/keys.go, database/database.go, database/database_test.go, database/json_file_storage.go, database/json_file_storage_test.go, database/mocks/mock_database.go, main/main.go, messages/message_manager.go, messages/off-chain-registry/message_manager.go, messages/teleporter/message_manager.go, relayer/message_relayer.go, relayer/message_relayer_test.go, relayer/relayer.go, relayer/relayer_test.go, tests/basic_relay.go, tests/e2e_test.go, tests/manual_message.go, tests/shared_db.go, tests/teleporter_registry.go, tests/utils/utils.go, utils/utils.go
Fixes #240 
- `messageRelayer` instances are persisted, and now pertain to a unique (source chain, destination chain, source address, destination address) tuple
- `Relayer` instances are composed of a set of `messageRelayers`, rather than `messageRelayer` being composed of the parent `Relayer`
- Migrates database interfacing methods from `Relayer` to `messageRelayer`
- Database keys changed from `ids.ID` to `common.Hash`
- Adds `DestinationAddress` and `SourceAddress` getters to `MessageManager` to facilitate key construction
- Adds database key utilities
- CI, updated tests
- Added multiple relayers, single DB e2e test
- TODO: New unit tests
Updated README
=> Support shared DB access

.github/workflows/snyk.yml, scripts/versions.sh
Fixes the snyk workflow, and bumps the golang patch version to the latest 1.21 release.
See https://github.com/github/codeql-action/issues/2187#issuecomment-2043220400
CI
N/A
=> Snyk upload fix

vms/evm/signer/kms_signer.go, vms/evm/signer/kms_signer_test.go
Fixes a bug in the KMS signature recovery logic where we were not capping the signature's s-value according to [EIP-2](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.md#specification).
Ensures that the signature's s-value is not greater than `secp256k1n/2`. See reference implementation here: https://github.com/welthee/go-ethereum-aws-kms-tx-signer/blob/main/signer.go#L79
Manually verified previously invalid signatures are now valid with the s-value cap.
N/A
=> EIP-2 cap s-value

README.md, config/config.go, config/test_utils.go, peers/utils/utils.go
Adding http-headers for p-chain and info-api clients.
Related to  https://github.com/ava-labs/awm-relayer/issues/186
Use mechanism introduced in #268 to pass http-headers to p-chain & info-api clients.
Details of the new Config fields are added in the README.
=> Rpc options

.goreleaser.yml
Fixes #282 
Adds configuration for a manifest named `latest` in `.goreleaser.yml`
Manually tested with a dummy tag. See the workflow run here: https://github.com/ava-labs/awm-relayer/actions/runs/9020169707/job/24784727290, which pushed the manifests [latest](https://hub.docker.com/layers/avaplatform/awm-relayer/latest/images/sha256-e22fdfa8f5286604f352cac56ce6e677714f2b5432adaa70044113a692982916?context=explore) and [v1.2.1-test](https://hub.docker.com/layers/avaplatform/awm-relayer/v1.2.1-test/images/sha256-e22fdfa8f5286604f352cac56ce6e677714f2b5432adaa70044113a692982916?context=explore) to the dockerhub repo.
N/A
=> Tag docker release as latest

.github/workflows/linter.yml, .github/workflows/test.yml, README.md, config/config.go, config/config_test.go, config/flags.go, config/keys.go, config/viper.go, main/main.go
Fixes a unit test that was merged to main.
Modifies the lint and unit test CI jobs to run on PRs originating from forks.
Adds a `--help` option to display proper usage. Usage is displayed if incorrect flags are passed to the application.
See above
CI
Updated README
=> Help option + fix unit test

database/relayer_id.go, main/main.go, relayer/listener.go, vms/evm/destination_client.go
Integrates the first 3 bullet points from this comment https://github.com/ava-labs/awm-relayer/pull/288#discussion_r1619465642
The main function now creates the application relayers instead of the listener. The application relayers are then passed to the listener instance.
=> Refactor application relayers

.goreleaser.yml, vms/evm/destination_client.go
Logs nonce usage to aid debugging.
Also enables support for prerelease tags (e.g. rc's)
=> Log nonce usage

.github/workflows/e2e.yml, .github/workflows/linter.yml, .github/workflows/release.yml, .github/workflows/snyk.yml, .github/workflows/test.yml, go.mod
Bumps the Golang version used by the relayer application, and bumps the Ubuntu versions that the Github actions run on.
=> Bump Golang and Ubuntu

vms/evm/destination_client_test.go, vms/evm/signer/signer.go, vms/evm/signer/tx_signer.go, vms/evm/signer/tx_signer_test.go
Only the key is required to create the signer, so pass it in instead of a whole Source Subnet config object. This was helpful when trying to recreate a warp transaction that had failed.
=> Only require key to create signer

relayer/application_relayer.go
Adds additional logs in the signature collection code to aid debugging.
=> Add signature collection logs

docs/architecture.md, docs/sequence.md
Adds architecture and sequence diagrams pertaining to online message relaying. Does not cover the catch up mechanism or manual Warp messages for simplicity.
Adds mermaid diagrams
=> Add architecture and sequence diagrams

README.md, config/destination_blockchain.go, config/source_blockchain.go, main/main.go, relayer/application_relayer.go, relayer/application_relayer_metrics.go, relayer/listener.go, tests/e2e_test.go, tests/utils/utils.go, tests/warp_api.go, utils/client_utils.go, vms/evm/destination_client.go
Fixe #119. Exposes config options to fetch Warp message aggregate signatures via the Warp API rather than app request.
Adds `SourceBlockchain.WarpAPIEndpoint` config option. Internally, `ApplicationRelayers` are composed of `[rpc.Client](https://github.com/ava-labs/subnet-evm/blob/master/rpc/client.go)` rather than `[warp.Client](https://github.com/ava-labs/subnet-evm/blob/master/warp/client.go)`. This is because `warp.Client` does not presently support query params or http headers, and expects the URI to be in a specific form.
Added Warp API e2e test.
Updated README
=> Warp API support

.github/workflows/e2e.yml, .github/workflows/linter.yml, .github/workflows/release.yml, .github/workflows/snyk.yml, .github/workflows/test.yml, CONTRIBUTING.md, go.mod
Bump to latest 1.21 Golang release. Removes unnecessary explicit version used by actions/setup-go in favor of pulling directly from go.mod.
=> Golang 1.21.12

.gitignore
Should fix the release workflow (current error seen [here](https://github.com/ava-labs/awm-relayer/actions/runs/9811964547/job/27098592954#step:11:27)).
The issue was introduced by this PR which no longer cloned the `awm-relayer` repo into it's own subdirectory, making the working directory the repository itself.
Documentation on the exact `goreleaser` error is [here](https://goreleaser.com/errors/dirty/).
=> Add osxcross to gitignore

README.md, api/relay_message.go, config/destination_blockchain.go, config/source_blockchain.go, utils/utils.go, utils/utils_test.go
Closes https://github.com/ava-labs/awm-relayer/issues/355
If the string is prepended by '0x', attempts to decode from hex. Otherwise, tries to decode as cb58. The checksum in cb58 should prevent accidental collisions.
Unit tests added
Added hex as option in README
=> Decode hex or cb58

tests/e2e_test.go
Because it reduced my test run time from 5m10s to 4m45s, an 8% reduction.
By running the existing tests.
=> e2e tests: use fewer nodes

.github/workflows/e2e.yml
Fixes the YAML syntax.
Uses spaces, not tabs
=> Fix YAML syntax

relayer/application_relayer.go, signature-aggregator/aggregator/aggregator.go, signature-aggregator/api/api.go, tests/signature_aggregator_api.go, tests/utils/utils.go
Because it fixes #381 
With the tests in the code base
=> Signature aggregation API fixes for small items

config/config.go, config/config_test.go
Closes #399 
This checks that the provided subnets does not exceed the limit (16) and returns error during config validation when exceeding.
unit test has been added
=> config: check tracked subnets does not exceed the limit

main/main.go, relayer/application_relayer.go
This is decoupling relayer and checkpoint manager implementation.
It reduces the number of args in the relayer factory as they were just used to instantiate checkpoint manager.
Now, the checkpoint manager is injected in the relayer factory as a dependency.
It uses the existing tests.
=> decoupling relayer and checkpointmanager implementation

messages/teleporter/message_handler.go, messages/teleporter/message_handler_test.go, tests/batch_relay.go
Adds an explicit check against the gas limit specified in the Teleporter message.
It's possible for the required gas limit in a Teleporter message to exceed the block gas limit. This causes the transaction to fail as expected, but also causes the relayer to enter an unhealthy state, preventing it from updating the checkpoint in its database. This can cause compounding latency that will eventually prevent the relayer from running at all.
Generally speaking, such validity checks are done in `ShouldSendMessage` and the `Decider` service. This is done before 
signature aggregation, to short circuit that step if the message is invalid. However, the number of signers impacts the gas estimation, so we can't use that in `ShouldSendMessage`. Instead, I added a hard cap of 12 million gas, which is …
=> Add explicit gas check

relayer/listener.go, relayer/message_coordinator.go
Currently, the message coordinator singleton dispatches to _every_ block from _every_ chain to _every_ application relayer. If there are messages in the block, they will still be processed as expected by the appropriate application relayer, and the other application relayers are very likely to simply no-op. However, if there are no messages in the blocks, then all application relayers will instead stage the height to be committed to the database. The committed heights will be out of order since they don't pertain to the expected chain, so no heights will be written. This breaks block checkpointing, and can cause OOM as the queue of pending blocks grows unbounded.
The message coordinator only dispatches to application relayers whose source chain ID matches the block being processed.
CI. …
=> Only write to listener's app relayers

relayer/listener.go, vms/evm/subscriber.go, vms/evm/subscriber_test.go, vms/subscriber.go
Addresses #443
- Switches catchup from using WS client that is available on the subscriber level to the RPC client used on the listener level. This means that WS issues that subscriber handles by reconnecting should no longer affect the catchup mechanism
- ~~Moves catchup process from subscriber to listener along with the headers channel~~
- Adds simple retries to the network request. 
~~After doing this I realized that this change can be made lighter by passing in an RPC client to the Subscriber as well. That would mean that we can keep the catchup and the headers on the subscriber level.~~
I pivoted to keeping things on the subscriber level and just changing the client and adding retries there
CI
N/A
=> Listener catch-up fix 

relayer/main/main.go
As of `avalanchego v1.11.7` it's no longer valid for nodes to set the primary network ID in their tracked subnets. Setting it anyway causes peers to disconnect from the relayer at the 22.5 second Ping interval. 
Only sets non-primary networkIDs as tracked subnets
Manually ran a relayer connected to fuji/echo/dispatch and confirmed that there are no disconnects when looking at the logs after this fix and there are without it. 
N/A
=> Tracked subnets fix

peers/app_request_network.go, peers/app_request_network_metrics.go, peers/external_handler.go
Instead of moving Connected/Disconnected log events back to info level this collects metrics on the number of connect and disconnect events that occur. As of now, the applications don't initiate any disconnects so alerts can be created to monitor for excessive disconnects initiated by network peers. 
Also fixed the typo in the `app_request_network_metrics.go` filename
I re-used recently added `AppRequestNetworkMetrics` struct since these are fundamentally still related to the `AppRequestNetwork`.
=> add metrics for connect/disconnect events

signature-aggregator/aggregator/aggregator_test.go
Fixes the success case unit test added in #467 
The mock validator set that is generated in the unit test needs to be properly ordered such that `nodeValidatorIndexMap` that is created is correct. Otherwise the bit set included in the Warp signature will not point to the correct public keys.
QED
N/A
=> Order mock validator set

signature-aggregator/api/api.go, utils/utils.go, utils/utils_test.go
it moves supporting func isEmptyOrZeroes into utils and exposes it to be used in avalanche-cli
also adds unittest for it
drop in replacement 
using unittest 
n/a
=> nit: move isEmptyOrZeroes to utils and added unittest for it

README.md, relayer/Dockerfile, signature-aggregator/Dockerfile
Issues were encountered when trying to run the docker images built by the new release flow. This fixes the problems and polishes a few other things along the way.
by running the commands shown in the readme, and by pushing a `...-dev` release tag, which triggered the CI job [here](https://github.com/ava-labs/awm-relayer/actions/runs/10820990388/job/30022145358), which pushed the docker image to docker hub as `avaplatform/signature-aggregator:v0.1.0-rc1-dev` [here](https://hub.docker.com/layers/avaplatform/signature-aggregator/v0.1.0-rc1-dev/images/sha256-392651b9d5cbad9f3145488153179c5394d4983b3234dbfb0c034d01c9e06f0b?context=explore), and then by running the docker image with
```
$ docker pull avaplatform/signature-aggregator:v0.1.0-rc1-dev
...
$ docker run -v …
```
=> Fixup release flow

signature-aggregator/README.md, signature-aggregator/api/api.go
`writeJsonError` didn't actually correctly serialize errors since the anonymous struct it was marshalling didn't have exposed fields so it would marshall to an empty struct.
Added status code to distinguish to the caller between user input errors and server side errors. Requests resulting in 5xx level errors can be retried and may succeed in the future while 4xx errors represent malformed or invalid input.
compiled the binary and manually tested against Fuji with common user supplied error cases. Got valid error reponses like:
```
➜  Code ./sendBadTx.sh
HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Fri, 20 Sep 2024 14:16:14 GMT
Content-Length: 36
{"error":"Could not decode message"}%
```
Updated the docs
=> Add error HTTP status codes and fix error json marshal

peers/external_handler.go
We currently use `prometheus.DefaultRegisterer` as the registerer for metrics we don't intend to collect. `DefaultRegisterer` simply calls `NewRegistry()` at compile time. In situations that create `NewSignatureAggregator`s within the same application instance (such as Ginkgo test suites), this can cause the aggregator to fail with `AlreadyRegisteredError`.
Replaces `DefaultRegisterer` with `NewRegistry()` so that the no-op registry is created at runtime rather than compile time.
CI
N/A
=> Create default registry at runtime

.github/workflows/e2e.yml, README.md, scripts/e2e_test.sh, scripts/install_avalanchego_release.sh
Allows for easier custom avalanchego vs subnet-evm versions assuming they are compatible with each other
Updates both the github e2e as well as `./scripts/e2e_test.sh` runner to use avalanchego version from `./scripts/versions.sh` instead of using the version from `subnet-evm` repo. 
Existing tests should pass. 
Need to update README.md for the simplified flow
=> use local copy of install_avalanchego_release.sh

peers/app_request_network.go
Fixes a bug introduced in https://github.com/ava-labs/awm-relayer/pull/559 that does not use the configured RPC parameters when calling the P-Chain API on network startup. This causes deployments that utilize API tokens or query parameters to fail to start.
Fetches the configured RPC settings before calling the C-Chain client.
=> use rpc options when bootstrapping network

.github/workflows/release_awm_relayer.yml, .github/workflows/release_signature_aggregator.yml, relayer/.goreleaser.yml, signature-aggregator/.goreleaser.yml
I failed to realize that https://github.com/ava-labs/awm-relayer/pull/565 only fixed the ARM builds for awm-relayer. This fixes the signature-aggregator builds as well
=> Fix signature-aggregator arm builds

relayer/.goreleaser.yml, signature-aggregator/.goreleaser.yml
`go get` installation doesn't work with slashes in tag names.
=> remove slashes from tag-prefix

relayer/listener.go
Currently the healthcheck fatals immediately on failure. This means that for intermittent connection failures this leads to a race between the reconnect setting the status back to healthy before the healthcheck is called again. If the healthcheck is called before the reconnect then the process shuts down. 
Alternative and potentially cleaner approach would be to not have the healthcheck failure shut down the process but let the kubernetes or whatever manages the process to shut it down based on the failed check and additional conditions/thresholds. 
Doesn't set the status to unhealthy until the reconnect attempts have failed.
=> move setting to unhealthy after retries

.github/workflows/release_icm_relayer.yml, .github/workflows/release_signature_aggregator.yml
#575 removed them from the goreleaser prefix but GH actions still trigger off of tags with slashes. this fixes it.
=> Remove slashes from the tag-prefix for GH action trigger

go.mod, go.sum, peers/app_request_network.go, scripts/versions.sh, tests/e2e_test.go
Updates avago, subnet-evm and teleporter->icm-contracts. Avago and subnet point to commits in master (no tags yet). 
`icm-contracts` points to a commit on a branch due to circular dependency for now. 
It does not include the private IP network change. This is going to be added in #580
=> Etna release prep

go.mod, go.sum, peers/app_request_network.go, relayer/main/main.go, signature-aggregator/main/main.go
Currently AppRequest networks logs just go to stdout without having any option to modify this. 
This PR let the user pass in a logger so he can decide where to put them.
Note: depends on icm-contracts branch https://github.com/ava-labs/icm-contracts/tree/pass-a-logger-to-new-network to pass CI
=> pass a logger to NewNetwork, so as to give control on where to redirect the logs

relayer/application_relayer.go, utils/backoff.go, vms/evm/subscriber.go
https://github.com/ava-labs/icm-services/pull/593 added an exponential backoff utility, useful for spacing out RPC requests and signature aggregation attempts. The exponential backoff utility as well as the backoff library require that the supplied operation will terminate. Some operations that use the utility consumed `context.Background()` and so would not do so. 
Adds a timeout context to eth_subscribe and Warp API calls. 
CI
Improves backoff utility documentation
cc @najeal
=> Add timeout to remote ops

.github/workflows/release_icm_relayer.yml, .github/workflows/release_signature_aggregator.yml
Last build failed with a clang arg error and this goreleaser version is a suspect as mentioned here: https://github.com/ava-labs/subnet-evm/pull/1439
=> pin goreleaser to v2.5.1

signature-aggregator/aggregator/aggregator.go, signature-aggregator/aggregator/aggregator_test.go
Fixes a bug in handling empty SignatureResponses. This was introduced with ACP-118 support since the SignatureResponse only has a single Signature field with `omitempty` tag, meaning that the empty signature serializes to empty slice. 
Trying to unmarshal an empty slices however results in a runtime panic. 
E2E + added new unit test for `aggregator.unmarshalResponse`
=> Empty app response handling

peers/app_request_network.go, peers/app_request_network_test.go
Only track up to maxNumberSubnets at any given point 
use a `linked.Hashmap` to implement the LRU cache. 
New unit test + CI
=> Implement LRU tracking of subnets

peers/app_request_network.go, peers/mocks/mock_app_request_network.go, signature-aggregator/aggregator/aggregator.go, signature-aggregator/aggregator/aggregator_test.go
Passes in context to the PChain API calls to GetSubnetID and rewraps it with a 1 second timeout to prevent too many hanging requests during high traffic periods. 
CI
=> add context + timeout to GetSubnetID API calls

metrics/server.go, peers/app_request_network.go, relayer/main/main.go, signature-aggregator/main/main.go, signature-aggregator/metrics/metrics.go
- Registers p2p network metrics with the top-level gatherer
- Refactors the metrics server creation pattern with a shared `metrics.StartMetricsServer` that encapsulates the gatherer and server instantiation
See above
CI. Manual verification that all metrics are queryable via `/metrics`
N/A
=> Expose network metrics

utils/backoff.go
Noticed that the v1.6.3-rc3 relayers running are logging correct context fields  from inside the `utils.WithRetriesTimeout` but the `message` field is missing most likely because it's a reserved attribute. 
renames to a non-reserved value
=> rename log field to not use reserved name

tests/e2e_test.go, vms/evm/destination_client.go
Fixes #755 by fetching the pending nonce rather than the latest nonce on startup.
Uses `rpc. PendingBlockNumber` in the call to `eth_getTransactionCount`
CI
N/A
=> Fetch pending nonce

signature-aggregator/aggregator/aggregator.go
Partially addresses #758, separate PR will address the remaining P-chain calls since caching those is likely going to produce more discussion and need for testing.  
- Added a new lock protected map field to cache the result
- Reusing the same lock since we don't want to make this call more than once and when it's cached it's only locked for a negligible time to do the map lookup. 
Existing CI 
added a comment to the `SignatureAggregator` struct that the field is protected by the now multipurpose `subnetMapsLock`
=> Cache p-chain calls for IsL1 checks

messages/teleporter/message_handler.go, messages/teleporter/message_handler_test.go, relayer/README.md, relayer/config/destination_blockchain.go, vms/destination_client.go, vms/evm/destination_client.go, vms/mocks/mock_destination_client.go
Closes #761 
- Adds a new configuration option for the destination clients that if not provided defaults to the existing constant of 30 seconds.
- Replaces the inner timeout on the actual call to `TransactionReceipt` with a default RPC timeout and sets the outer one to this new configurable value
- Existing CI should pass
- Should probably add a test to `SendTx` but that should test cases beyond just this timeout
- New field documented in the README
=> configurable block acceptance timeout

vms/evm/destination_client.go, vms/evm/destination_client_test.go
Modifies https://github.com/ava-labs/icm-services/pull/764 to synchronize nonce access and transaction issuance using a condition variable rather than a decoupled lock and mutex.
The only functional difference is that on startup we block until all pending transactions have been processed, rather than handling that async. This has no meaningful effect on message relaying latency, since any new relay requests must wait for pending transactions to be accepted anyway before the message may be delivered in a new transaction.
=> throttle tx usage using condition variable

relayer/config/keys.go, signature-aggregator/config/keys.go
Both the relayer and the signature-aggregator include configuration keys that are declared but
never actually consumed by the application, which risks misleading developers into believing
certain features exist or are configurable.
In the relayer’s config/keys.go:
- PChainAPIKey
- InfoAPIKey
- SourceBlockchainsKey
- DestinationBlockchainsKey
- RedisURLKey
- ManualWarpMessagesKey
In the signature-aggregator’s config/keys.go:
- PChainAPIKey
- InfoAPIKey
To improve code maintainability and prevent potential confusion, consider removing the
constant definitions for any configuration keys that are not currently implemented or used by
the application.
=> N-09 Unused Keys

signature-aggregator/aggregator/aggregator.go
In the CreateSignedMessage function, a critical piece of logic is designed to filter out L1 validators that do not meet a specified balance threshold. However, the comment describing this logic is misleading and does not accurately represent the operation being performed. The [comment](https://github.com/ava-labs/icm-services/blob/11c6cafa6d5a8572a2f48364e850491db5c86b80/signature-aggregator/aggregator/aggregator.go#L268-L270) explaining a key part of this logic is misleading by stating:
> // This check will pass if either
> // 1) the node is an L1 validator with insufficient balance or
> // 2) the node is a non-L1 (legacy) validator
However, the opposite check is performed: the if statement evaluates to true if the node ID is not contained in the set of underfunded nodes. 
Consider …
=> N-05 Misleading Comment

peers/app_request_network.go, peers/app_request_network_test.go, peers/mocks/mock_app_request_network.go, peers/validators/canonical_validator_client.go, peers/validators/mocks/mock_canonical_validator_client.go, relayer/network_utils.go, signature-aggregator/aggregator/aggregator.go, signature-aggregator/aggregator/aggregator_test.go, signature-aggregator/api/api.go
The application's handling of context in API calls demonstrates an oversight in the propagation of timeouts and cancellations. This mismanagement significantly impacts the application's ability to respond promptly to upstream cancellations and timeouts, potentially leading to unnecessary resource utilization and degraded performance.
In the `canonical_validator_client.go` file, the [GetCurrentCanonicalValidatorSet](https://github.com/ava-labs/icm-services/blob/11c6cafa6d5a8572a2f48364e850491db5c86b80/peers/validators/canonical_validator_client.go#L53) method is tasked with retrieving the validator set for a given subnet from the P-Chain. Unlike other methods within the same file that correctly accept a `context.Context` from their callers, `GetCurrentCanonicalValidatorSet` independently …
=> N-03 Mismanagement of Context in API Calls Hinders Responsiveness

signature-aggregator/aggregator/cache.go
The [NewSignatureCache](https://github.com/ava-labs/icm-services/blob/11c6cafa6d5a8572a2f48364e850491db5c86b80/signature-aggregator/aggregator/cache.go#L24) function in the signature aggregator component is designed to initialize a cache for storing signatures. It takes a `size` parameter that limits the number of distinct message IDs (keys) that can be held in the cache at a time. This check is crucial for preventing the cache from growing indefinitely, which could lead to memory exhaustion issues.
The check in the constructor only constrains the number of keys in the cache, but it places nolimit on the size of the values. The value associated with each key is a `map[PublicKeyBytes]SignatureBytes`. The [Add](https://github.com/ava-labs/icm-services/blob/11c6cafa6d5a8572a2f48364e850491db5c …
=> N-10 Inadequate Cache Size Validation in Signature Aggregationadd limit to number of signatures

signature-aggregator/aggregator/aggregator.go, signature-aggregator/config/config.go
Throughout the codebase, multiple instances of unused code were identified that, if removed, could streamline the project and enhance its maintainability. Addressing these instances not only reduces the codebase's complexity but also minimizes potential confusion for developers navigating the project. Below are the specific recommendations for removal:
- The `GetNodeID` function and, therefore, the myNodeID field are unused. Consider removing the function and field.
- The `GetMinimumHeight` and `GetCurrentHeight` functions are unused, while the GetCurrentValidatorSet function is not needed. Consider removing these functions and adding the GetSubnetID function to the CanonicalValidatorState interface instead of validators.State. (Won't fix changing of the interfaces since we don't control …
=> N-06 Unused Code

relayer/checkpoint/checkpoint.go, relayer/checkpoint/checkpoint_test.go, relayer/config/config.go, relayer/main/main.go, signature-aggregator/aggregator/aggregator.go, signature-aggregator/api/api.go
Throughout the codebase, multiple opportunities for code simplification were identified. These recommendations span various components and functionalities, addressing both specific code segments and broader architectural patterns:
- Within the [initializeTrackedSubnets](https://github.com/ava-labs/icm-services/blob/11c6cafa6d5a8572a2f48364e850491db5c86b80/relayer/config/config.go#L248) function, the warp configuration per destination chain can be accessed through `destinationBlockchain.warpConfig` instead of through the 1GetWarpConfig` function.
- The `req.Message` could be sanitized with [SanitizeHexString](https://github.com/ava-labs/icm-services/blob/11c6cafa6d5a8572a2f48364e850491db5c86b80/utils/utils.go#L129), just like `req.Justification`.
- The …
=> N-04 Code Simplification Suggestions

signature-aggregator/aggregator/cache.go
The `cache.go` file implements a `SignatureCache` using a thread-safe LRU cache to store
BLS signatures for different messages. The SignatureAggregator uses this cache to
collect signatures from multiple validators before aggregating them.
The `Add` method is intended to add a new signature for a given `message ID` ( `msgID`). It first
checks if an entry for the `msgID` already exists. If not, it creates a new map, adds the
signature to it, and then stores the map in the cache. If an entry does exist, it retrieves the
existing map of signatures, adds the new signature to it, and writes the updated map back to
the cache. This `Add` method is called concurrently from the `handleResponse` function in
`aggregator.go`, as the aggregator processes signature responses from multiple peers in …
=> L-04 Race Condition in Signature Cache Leads to Lost Signatures

database/database.go, database/json_file_storage.go, database/mocks/mock_database.go, database/redis.go, database/utils_test.go, relayer/main/main.go, signature-aggregator/main/main.go
Both `main.go` [[1](https://github.com/ava-labs/icm-services/blob/11c6cafa6d5a8572a2f48364e850491db5c86b80/relayer/main/main.go), [2](https://github.com/ava-labs/icm-services/blob/11c6cafa6d5a8572a2f48364e850491db5c86b80/signature-aggregator/main/main.go)] applications follow a similar initialization pattern. They set up all required resources, such as the P2P network, database connections, and HTTP servers, and then conclude with a blocking call ( `errgroup.Wait()` for the relayer, `http.ListenAndServe` for the aggregator) that keeps the process alive. Cleanup functions, like network.Shutdown(), are scheduled using defer.
This application structure does not handle OS signals like `SIGINT` or `SIGTERM`. When the process receives one of these signals, it terminates immediately and …
=> L-05 Lack of Graceful Shutdown for OS Signals

tests/validators_only_network.go
This should hopefully fix the recent flakiness of this test. It looks like there is a recent regression in the time to dynamic discovery of new subnetID IPs making this test flaky. This should be an okay path since we will be changing the way that peers are discovered soon.
=> explicitly add subnet ID to tracked Subnets to fix E2E flakiness

relayer/main/main.go
Closes https://github.com/ava-labs/icm-services/issues/871
If we provide an empty decider url, `createDeciderConnection()` validly returns `nil`. This then gets used to make an `emptyDeciderClient` in `NewMessageHandlerFactory`. When the defer is run on the the `nil`, it panics.
We could probably return some sort of empty decider connection object instead, but this is a quick and easy fix.
=> Fix panic on shutdown
